### ISSUE TITLE
'run' method broken in Ubuntu 14.04 in Version 0.3.8

### ISSUE THREAD

**Issue by sheinz** [theiviaxx/python-perforce#20]
The run method throws exception:

    FileNotFoundError: [Errno 2] No such file or directory: 'p4 -u user_name -p 127.0.0.1:1666 -c client name -G login'

It is recommended to pass a sequence to **subprocess.Popen** otherwise the behaviour is platform dependent.
https://docs.python.org/3/library/subprocess.html#popen-constructor

**Comment by theiviaxx** [comment]
the Connection and connect() function take an 'executable' argument.  It defaults to 'p4' so if that isn't on your path, you'll need to provide the full path to connect or add it to your path.

https://github.com/theiviaxx/python-perforce/blob/master/perforce/models.py#L99

**Comment by sheinz** [comment]
p4 is in my path, I can ran it from the shell.
I had to apply the patch to continue using **python-perforce** library.
The patch reverts changes in **run** method.

[models-patch.txt](https://github.com/theiviaxx/python-perforce/files/92641/models-patch.txt)

**Comment by theiviaxx** [comment]
ok i'll take a look and test it out on linux.  Reverting that change breaks filenames with spaces so i'll have to see what is going on

**Comment by theiviaxx** [comment]
ok, so as you pointed out in the first comment, i changed the call to subprocess to use a list instead of a string.  I added a deprecation warning if strings are passed in.  i was fighting python trying to help me :/
