### ISSUE TITLE
Error getting environment variables. 

### ISSUE THREAD

**Issue by sheinz** [theiviaxx/python-perforce#27]
There's an error on Ubuntu14.04 and python-perforce (0.3.12):

    import perforce
    p4 = perforce.Connection()
    ...
    FileNotFoundError: [Errno 2] No such file or directory: 'p4 set'

It seems like subprocess.check_output accepts a list. Not a string with arguments separated by spaces:

    from subprocess import check_output
    check_output('p4 set')
    ...
    FileNotFoundError: [Errno 2] No such file or directory: 'p4 set'

    check_output(['p4', 'set'])
    b'P4CLIENT=....\nP4USER=...\n'

**Comment by sheinz** [comment]
From [documentation](https://docs.python.org/3/library/subprocess.html#subprocess.Popen):
> On POSIX, if args is a string, the string is interpreted as the name or path of the program to execute. However, this can only be done if not passing arguments to the program.

**Comment by theiviaxx** [comment]
you're correct, i made this change for the .run() function but not this :(  i'll fix this tonight
